welcome_message_available: true
spawn_point:
    count: 8
spawn_point_1:
    color: "white"
    asigned: false
    x: -50000
    y: -50000
spawn_point_2:
    color: "black"
    asigned: false
    x: -50000
    y: 0
spawn_point_3:
    color: "purple"
    asigned: false
    x: -50000
    y: +50000
spawn_point_4:
    color: "blue"
    asigned: false
    x: 0
    y: +50000
spawn_point_5:
    color: "cyan"
    asigned: false
    x: +50000
    y: +50000
spawn_point_6:
    color: "green"
    asigned: false
    x: +50000
    y: 0
spawn_point_7:
    color: "yellow"
    asigned: false
    x: +50000
    y: -50000
spawn_point_8:
    color: "red"
    asigned: false
    x: 0
    y: -50000