main: main.BasicUtilities
version: 1.0.1
name: BasicUtilities

commands:
    utils:
        description: Principal command that handle the config.
    location:
        description: Command that handles the locations.
    starterpack:
        description: Comand that handles the starter equipment.
    stp:
        description: Comand that handles the starter equipment.